name: Trigger auto deployment for medai9faf8629

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/medai9faf8629-AutoDeployTrigger-0d0d947e-da97-4b91-b0c3-b32f157ed236.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MEDAI9FAF8629_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MEDAI9FAF8629_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MEDAI9FAF8629_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.MEDAI9FAF8629_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MEDAI9FAF8629_REGISTRY_PASSWORD }}
          containerAppName: medai9faf8629
          resourceGroup: medai9faf
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


